/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('post').del()
  await knex('post').insert([
    {userid:2, title: 'hello world', date: '1996-12-12',content : 'something cool'},
    {userid:1, title: 'More Content', date: '2020-07-17', content : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dictum at tempor commodo ullamcorper. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Ut lectus arcu bibendum at varius vel pharetra. Amet commodo nulla facilisi nullam. Suspendisse in est ante in nibh. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Tristique risus nec feugiat in fermentum posuere urna. Velit laoreet id donec ultrices tincidunt. Dictum varius duis at consectetur lorem donec massa. Laoreet non curabitur gravida arcu ac tortor dignissim. Elementum curabitur vitae nunc sed velit dignissim sodales. Ac odio tempor orci dapibus ultrices in iaculis. Quisque sagittis purus sit amet. Habitant morbi tristique senectus et. Quis viverra nibh cras pulvinar.'},
    {userid:1, title: 'Example of a little longer title right here', date: '2011-11-11', content : 'Nunc scelerisque viverra mauris in. Consequat semper viverra nam libero justo laoreet sit. Enim eu turpis egestas pretium. Risus feugiat in ante metus dictum at. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Sapien eget mi proin sed libero enim sed faucibus turpis. Sit amet massa vitae tortor condimentum. In arcu cursus euismod quis viverra nibh cras pulvinar. Montes nascetur ridiculus mus mauris. Amet venenatis urna cursus eget nunc scelerisque. Sed risus pretium quam vulputate dignissim suspendisse. Mattis rhoncus urna neque viverra. Ultricies leo integer malesuada nunc vel risus commodo viverra. Semper risus in hendrerit gravida. Volutpat est velit egestas dui id. Dictumst vestibulum rhoncus est pellentesque elit. Turpis egestas integer eget aliquet nibh praesent tristique magna sit.'},
    {userid:3, title: 'Great Blog Post', date: '2022-07-01', content : 'Et leo duis ut diam. Justo eget magna fermentum iaculis eu non diam. Eu consequat ac felis donec et odio. Enim lobortis scelerisque fermentum dui faucibus in. Praesent elementum facilisis leo vel fringilla est. Blandit cursus risus at ultrices mi tempus. Orci nulla pellentesque dignissim enim sit amet venenatis. Vestibulum morbi blandit cursus risus at ultrices. Vulputate enim nulla aliquet porttitor lacus. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Sit amet consectetur adipiscing elit duis. Urna molestie at elementum eu facilisis sed odio morbi quis.'},
    {userid:3, title: 'Excellent Title', date: '2022-06-30', content : 'Risus viverra adipiscing at in tellus integer. Velit dignissim sodales ut eu sem integer. Massa enim nec dui nunc. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Diam quis enim lobortis scelerisque fermentum dui faucibus. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Gravida quis blandit turpis cursus in hac habitasse. Volutpat blandit aliquam etiam erat velit scelerisque in. Semper risus in hendrerit gravida rutrum quisque non tellus. Ut tortor pretium viverra suspendisse potenti nullam ac tortor.'}
  ]);
};
